[game]
title="Adventures of Demo"
id="aod"

[characters]
name1="Demo"
name2="Iris"
name3="Kood"
name4="Raocow"
name5="Sheath"

[credits]
font=4
homepage="wohlsoft.ru"
; New format of credits - directly from text file
game-credits-file="credits.txt"

; Old format of credits - lines defined here, kept for backward compatibility for old TheXTech versions
; credits.txt begin
game-credit-1="Adventures of Demo by Wohlstand"
game-credit-2=""
game-credit-3="Stuff by raocow and his fan community:"
game-credit-4="talkhaus.raocow.com"
game-credit-5=""
game-credit-6="Characters By:"
game-credit-7="Cadwyn"
game-credit-8="Chaoxys"
game-credit-9="darkychao"
game-credit-10="Jolpengammler"
game-credit-11="Mata Hari"
game-credit-12="MrWeirdGuy"
game-credit-13="raocow"
game-credit-14="Roo"
game-credit-15="Tsurugi"
game-credit-16=""
game-credit-17="Graphics By:"
game-credit-18="Cadwyn"
game-credit-19="Chaoxys"
game-credit-20="darkychao"
game-credit-21="Enjl"
game-credit-22="Feenicks"
game-credit-23="Frozelar"
game-credit-24="Hoeloe"
game-credit-25="Mata Hari"
game-credit-26="MrWeirdGuy"
game-credit-27="Paralars"
game-credit-28="Quine"
game-credit-29="raocow"
game-credit-30="RedYoshi"
game-credit-31="rixithechao"
game-credit-32="SAJewers"
game-credit-33="SilverDeoxys563"
game-credit-34="supermarioman"
game-credit-35="Terry Von Feleday"
game-credit-36="Various members of Talkhaus"
game-credit-37="Wohlstand"
game-credit-38=""
game-credit-39="Music By:"
game-credit-40="A13XIS"
game-credit-41="Amber Vasami"
game-credit-42="Aristo"
game-credit-43="BaDLiZ"
game-credit-44="Chrom1um"
game-credit-45="d.r.m of disknet"
game-credit-46="Dr.Tapeworm"
game-credit-47="Izuna"
game-credit-48="Kil"
game-credit-49="Lui37"
game-credit-50="Mandew"
game-credit-51="Michail Oberuechtin"
game-credit-52="necros/fm"
game-credit-53="Prsynth1111"
game-credit-54="Razmatan_iki"
game-credit-55="RednGreen"
game-credit-56="Robert A. Allen"
game-credit-57="Roberto Ricioppo"
game-credit-58="Rondo"
game-credit-59="SharkNurse"
game-credit-60="Sinc-X"
game-credit-61="S.N.N."
game-credit-62="ThinkOneMoreTime"
game-credit-63="Torchkas"
game-credit-64="Various authors at modarchive.org"
game-credit-65="WhiteYoshiEgg"
game-credit-66="Wohlstand"
game-credit-67="Woolters"
game-credit-68=""
game-credit-69="SFX By:"
game-credit-70="Hoeloe"
game-credit-71="rixithechao"
game-credit-72="Wohlstand"
game-credit-73="or from public domain"
; credits.txt end
